// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB79bmwHQKVvuB3zbDNevHUViHThmKSCnI',
    appId: '1:571991627129:web:5c0bbf7db537fda64a0ba8',
    messagingSenderId: '571991627129',
    projectId: 'parkgsu-11fc1',
    authDomain: 'parkgsu-11fc1.firebaseapp.com',
    storageBucket: 'parkgsu-11fc1.appspot.com',
    measurementId: 'G-2E387YK9QZ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBpf67uKjdPBtsBTC17Xak_i0YReyKjFM',
    appId: '1:571991627129:ios:1db23933944ffbf54a0ba8',
    messagingSenderId: '571991627129',
    projectId: 'parkgsu-11fc1',
    storageBucket: 'parkgsu-11fc1.appspot.com',
    iosBundleId: 'com.example.parkgsu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBpf67uKjdPBtsBTC17Xak_i0YReyKjFM',
    appId: '1:571991627129:ios:1db23933944ffbf54a0ba8',
    messagingSenderId: '571991627129',
    projectId: 'parkgsu-11fc1',
    storageBucket: 'parkgsu-11fc1.appspot.com',
    iosBundleId: 'com.example.parkgsu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB79bmwHQKVvuB3zbDNevHUViHThmKSCnI',
    appId: '1:571991627129:web:3b12d09504f561f24a0ba8',
    messagingSenderId: '571991627129',
    projectId: 'parkgsu-11fc1',
    authDomain: 'parkgsu-11fc1.firebaseapp.com',
    storageBucket: 'parkgsu-11fc1.appspot.com',
    measurementId: 'G-R0T6YEC1PR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA961tYZGkhEivkU2uuufJnd4DhnpVNgY8',
    appId: '1:571991627129:android:42071f0e506b12dd4a0ba8',
    messagingSenderId: '571991627129',
    projectId: 'parkgsu-11fc1',
    storageBucket: 'parkgsu-11fc1.appspot.com',
  );

}