name: parkgsu
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.0.0
  firebase_core: ^3.3.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.2.1
  geolocator: ^13.0.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geocoding: ^2.0.4
  webview_flutter: ^4.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
